name: Publish Plugin to WordPress.org
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Install dependencies & build assets
      shell: bash
      run: |
        npm install
        npm run build:prod

    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Generate POT file
      shell: bash
      run: composer run pot

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@2.3.0
      with:
        generate-zip: 'true'
        dry-run: ${{ startsWith(github.ref, 'refs/tags/dry') }}
      env:
        SLUG: 'godam'
        ASSETS_DIR: 'wp-assets'
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        VERSION: '${{ github.ref_name }}'
    - name: Upload Test Artifact
      if: startsWith(github.ref, 'refs/tags/dry')
      uses: actions/upload-artifact@v4.6.1
      with:
        name: godam
        path: '${{ steps.deploy.outputs.zip-path }}'
    - name: Upload Release Artifact
      if: startsWith(github.ref, 'refs/tags/dry') == false
      uses: softprops/action-gh-release@v2.2.1
      with:
        files: |
          ${{ steps.deploy.outputs.zip-path }}
        token: '${{ github.token }}'
        tag_name: ${{ github.ref_name }}
        draft: true
